version: '3'

services:
  streamlit:
    build: .
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=true
      - STREAMLIT_SERVER_COOKIE_SECRET=my_secret_cookie
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
